const products=[
  {
   name: 'Free Shirt 1',
   category:'Shirts',
   image:['assets/images/product/1-1.jpg', 'assets/images/product/1-1.jpg'],
   price:70,
   brand:'Nike',
   rating:4.5,
   numReviews:10,
   countInStock:20,
   description:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis ostrud exercitation ullamco,Proin lectus ipsum, gravida et mattis vulputate, tristique ut lectus',
  },
  {
   name: 'Free Shirt 2',
   category:'Pants',
   image:['assets/images/product/1-1.jpg', 'assets/images/product/1-2.jpg'],
   price:70,
   brand:'Nike',
   rating:4.5,
   numReviews:10,
   countInStock:20,
   description:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis ostrud exercitation ullamco,Proin lectus ipsum, gravida et mattis vulputate, tristique ut lectus',
  },
  {
   name: 'Free Shirt 3',
   category:'Shirts',
   image:['assets/images/product/1-1.jpg', 'assets/images/product/1-1.jpg'],
   price:70,
   brand:'Nike',
   rating:4.5,
   numReviews:10,
   countInStock:20,
   description:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis ostrud exercitation ullamco,Proin lectus ipsum, gravida et mattis vulputate, tristique ut lectus',
  },
  {
   name: 'Free Shirt 4',
   category:'Pants',
   image:['assets/images/product/1-1.jpg', 'assets/images/product/1-1.jpg'],
   price:70,
   brand:'Nike',
   rating:4.5,
   numReviews:10,
   countInStock:20,
   description:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis ostrud exercitation ullamco,Proin lectus ipsum, gravida et mattis vulputate, tristique ut lectus',
  },
  {
   name: 'Free Shirt 5',
   category:'Shirts',
   image:['assets/images/product/1-1.jpg', 'assets/images/product/1-1.jpg'],
   price:70,
   brand:'Nike',
   rating:4.5,
   numReviews:10,
   countInStock:20,
   description:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis ostrud exercitation ullamco,Proin lectus ipsum, gravida et mattis vulputate, tristique ut lectus',
  },
  {
   name: 'Free Shirt 6',
   category:'Pants',
   image:['assets/images/product/1-1.jpg', 'assets/images/product/1-1.jpg'],
   price:70,
   brand:'Nike',
   rating:4.5,
   numReviews:10,
   countInStock:20,
   description:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis ostrud exercitation ullamco,Proin lectus ipsum, gravida et mattis vulputate, tristique ut lectus',
  },
  {
   name: 'Free Shirt 7',
   category:'Shirts',
   image:['assets/images/product/1-1.jpg', 'assets/images/product/1-1.jpg'],
   price:70,
   brand:'Nike',
   rating:4.5,
   numReviews:10,
   countInStock:20,
   description:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis ostrud exercitation ullamco,Proin lectus ipsum, gravida et mattis vulputate, tristique ut lectus',
  },
 ]


export default products;